### ISSUE TITLE
Workflow being disabled even though v2 is in use

### ISSUE THREAD

**Issue by rfay** [gautamkrishnar/keepalive-workflow#36]
This is apparently different from @julienloizelet 's 
* #34

I just got the warning from GitHub that my workflows on https://github.com/rfay/ddev-drushonhost are about to be disabled.

As [you can see there](https://github.com/rfay/ddev-drushonhost/actions/runs/9109009849) the scheduled tests have been running; there's only one workflow, and it's using v2 of this action.

This is using https://github.com/ddev/github-action-add-on-test v2, which uses gautamkrishnar/keepalive-workflow v2

I'd love to know what you think is going on. 

I do have other projects with identical single workflow (like https://github.com/ddev/signing_tools/ and https://github.com/ddev/ddev-redis-commander ) that are now more than 2 months out and not disabled yet.

**Comment by gautamkrishnar** [comment]
@rfay this is an interesting use case. I haven't looked into this use case yet.  

I mostly developed this action assuming that it's used directly in the repo that the action needs to keep alive.  In this case https://github.com/rfay/ddev-drushonhost, I haven't thought about it being used under a nested action. 

I will take a look at this when I get some time. Thanks for reporting it.

**Comment by gautamkrishnar** [comment]
@rfay I just checked. it should work just fine.  From the action output i can see that the action is getting ran correctly and is producing a valid output: 

https://github.com/rfay/ddev-drushonhost/actions/runs/9125279845/job/25091133605
![Screenshot 2024-05-18 at 2 13 34 AM](https://github.com/gautamkrishnar/keepalive-workflow/assets/8397274/3e1672e7-0eac-499c-934c-6be36e83677d)

The email you got might be most probably a GitHub Bug. I am not sure. It also looks like the scheduling is still working just fine in the repo. Lets wait for the deadline and see if the action is getting disabled or not.

I think I can add some more descriptive message about which file the action kept alive instead of just showing `parent workflow`. FIxing it right away.

**Comment by gautamkrishnar** [comment]
@rfay i just released a release that outputs parent workflow's name when keeping it active. 

Let's wait and see if the workflow is somehow getting disabled. If it's not feel free to close this jira.

**Comment by julienloizelet** [comment]
@gautamkrishnar ,

I was wondering if the `time_elapsed` is taken into account by your action when using the api call?

If so, since @rfay's action uses 55 as `time_elapsed` and GitHub sends a warning before those 55 days, this could explain the behavior seen. 
For info, last commit was on March 24 and March 24 + 55 days = May 18 (today).

Yesterday (and the day before because it was not yet 55 days after the last commit), we can see in the logs: 
`Nothing to do`

Today, we see: 
`Kept repo active using GitHub API`


But, then, I have other questions/remarks: 

1) While 55 was a good default value for your v1 action (because it limits the number of fictitious commitments), why should we have such a default value with v2? I think 0 might be a good candidate. (In fact, I don't even think we should use this time_elapsed value and always make a call to the api, as I don't see what the problem could be with this).

2)  The documentation on `time_elapsed` states: `Time elapsed since the previous commit to trigger a new automated commit (in days)` . Therefore, it is not mentioned that it will also be used to trigger the api call. 

3) As there will be no further commits with the v2 api call, the "time elapsed since the previous commit" will not change. Does this mean that the api call will be made on each new workflow run? Or is the time elapsed since the last "keep alive" call taken into account?

Thanks

**Comment by gautamkrishnar** [comment]
@julienloizelet time_elapsed is taken into consideration on v2 as well. 

> While 50 was a good default value for your v1 action (because it limits the number of dummy commits), why should we have such a default value with v2? I think 0 might be a good candidate. (In fact, I don't even think we should use this time_elapsed value and always make a call to the api, as I don't see what the problem could be with this).

My intention here was to call the API only when it's needed. It is not needed to call the API if the Last commit is not older than 60 days. 

> If so, since @rfay's action uses 55 as time_elapsed and GitHub sends a warning before those 55 days, this could explain the behavior seen. 

Thanks a lot for debugging it. I never knew this. Looks like setting a shorter time is OK. Thanks a lot for creating a PR to fix it.

> The documentation on time_elapsed states: Time elapsed since the previous commit to trigger a new automated commit (in days) . Therefore, it is not mentioned that it will also be used to trigger the api call.

Documentation needs some update. Thanks for noting it.

**Comment by gautamkrishnar** [comment]
@all-contributors please add @rfay for bug and @julienloizelet for bug

**Comment by vkt1414** [comment]
@gautamkrishnar 
thanks for this great gha. 
I do have a similar question. I'm using your action as a standalone gha to keep our gha's running, and was hoping it would work. But it does not seem to. I do not if I'm missing something. Even though it says..`Kept repo active using the GitHUb API...` Our gha were disabled for about 3 weeks now. Could you take a look whenever possible? We would really appreciate it.

https://github.com/ImagingDataCommons/github_analytics/actions/runs/9769562975/job/26969236102

**Comment by vkt1414** [comment]
> @gautamkrishnar thanks for this great gha. I do have a similar question. I'm using your action as a standalone gha to keep our gha's running, and was hoping it would work. But it does not seem to. I do not know if I'm missing something. Even though it says..`Kept repo active using the GitHUb API...` Our gha were disabled for about 3 weeks now. Could you take a look whenever possible? We would really appreciate it.
> 
> https://github.com/ImagingDataCommons/github_analytics/actions/runs/9769562975/job/26969236102

I think I realize now. Your action must be included on every gha, as a separate job, if we are using API method I guess. I'll simply use `use_api: false` so that I can use action only once for the entire repo.
